name: Build TWA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip

          unzip commandlinetools-linux-11076708_latest.zip -d $HOME/android-sdk/cmdline-tools/
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34"

      - name: Install latest Bubblewrap (force upgrade)
        run: |
          npm uninstall -g @bubblewrap/cli || true
          npm install -g @bubblewrap/cli@latest
          bubblewrap --version

      - name: Init TWA (CI mode)
        env:
          ANDROID_HOME: ${{ github.workspace }}/../android-sdk
          BUBBLEWRAP_CI: "1"
        run: |
          bubblewrap init \
            --manifest=https://powertech0417.github.io/generate_links/manifest.json \
            --skip-requirements-check \
            --use-existing \
            --ci

      - name: Build TWA
        env:
          BUBBLEWRAP_CI: "1"
        run: bubblewrap build --ci --skip-requirements-check

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app-release-signed.apk
